In [106]:
import arcpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

DBPATH=r"C:\Users\mike\Documents\OSU\GEOG561\Project - Florida Scrub Zone\FL_Zone_9a_9b_Scrub_Incursion_Restoration\FL_Zone_9a_9b_Scrub_Incursion_Restoration.gdb"
arcpy.env.workspace=DBPATH

In [107]:
knownScrubSpeciesObs = numpy.asarray(arcpy.da.TableToNumPyArray('csKnownScrubZone9', 'species').tolist()).flatten()
knownScrubSpeciesObsHist = (pd.Series(knownScrubSpeciesObs).value_counts())
knownScrubSpeciesObsHist

Serenoa repens            82
Palafoxia feayi           80
Ceratiola ericoides       75
Quercus geminata          68
Ximenia americana         66
Lyonia ferruginea         59
Asclepias tuberosa        59
Pinus clausa              56
Opuntia humifusa          55
Balduina angustifolia     54
Quercus myrtifolia        49
Vaccinium myrsinites      48
Hypericum tenuifolium     47
Bejaria racemosa          45
Quercus chapmanii         43
Pityopsis graminifolia    42
Persea humilis            35
Commelina erecta          34
Polygonella robusta       31
Carya floridana           31
Piloblephis rigida        31
Licania michauxii         29
Quercus inopina           26
Lyonia fruticosa          26
Dalea feayi               24
Yucca filamentosa         24
Ilex opaca                24
Sabal etonia              23
Asimina obovata           22
Cartrema floridana        13
Vaccinium darrowii        12
Chrysopsis floridana      11
Conradina grandiflora      9
Zamia integrifolia         5
Trichostema di

In [109]:
knownScrubSpeciesObsHistP = knownScrubSpeciesObsHist/len(knownScrubSpeciesObs)
knownScrubSpeciesObsHistP.plot(kind='bar')
plt.hlines((.01, .02, .03, .04, .05, .06), 0, 1000)
plt.title("Citizen Science Observations in Known Scrub Areas, Total Observations: %s" % len(knownScrubSpeciesObs)) 
plt.show()

In [103]:
clusterIds = numpy.asarray(arcpy.da.TableToNumPyArray('csScrubPlantsZone9Communities_poly', 'CLUSTER_ID').tolist()).flatten()
clusterIds

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
#This takes a few min to run.
plantCommunities = arcpy.da.TableToNumPyArray('csScrubPlantsZone9Communities',  ('CLUSTER_ID','species'))

In [168]:
#This also takes a few min to run.
plantCommunities_df = pd.DataFrame(plantCommunities)
plantCommunityHists = {}
plantCommunity = {}
for cluster_id in clusterIds:
    plantCommunity[cluster_id] = plantCommunities_df.loc[plantCommunities_df['CLUSTER_ID']==cluster_id]
    plantCommunityHists[cluster_id] = plantCommunity[cluster_id].value_counts()

IndexError: list assignment index out of range

In [118]:
for cluster_id in clusterIds:
    plantCommunityHists[cluster_id].plot(kind='bar')
    plt.title("Distribution of Citizen Science Observations in Cluster %s" % cluster_id) 
    plt.subplots_adjust(bottom=.5)
    plt.show()   


In [119]:
contigency = pd.crosstab(plantCommunities_df['CLUSTER_ID'], plantCommunities_df['species'])


species     Asclepias tuberosa  ...  Yucca filamentosa
CLUSTER_ID                      ...                   
1                            0  ...                  0
2                            1  ...                  0
3                            1  ...                  2
4                            0  ...                  1
5                            0  ...                  0
6                            3  ...                  4
7                            0  ...                  0
8                            0  ...                  2
9                            0  ...                  3
10                           0  ...                  1
11                           0  ...                  1
12                           3  ...                  2

[12 rows x 32 columns]

In [132]:
import scipy
stat, p, dof, expected = scipy.stats.chi2_contingency(contigency)
print(stat, p, dof)

1512.825711521683 6.433374686196485e-147 341


In [133]:
critical  = scipy.stats.chi2.ppf(.95, dof)
print(critical)

if abs(stat) >= critical:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

385.0621918877466
Dependent (reject H0)


In [237]:
plants=list(np.unique(knownScrubSpeciesObs))
plants

['Asclepias tuberosa', 'Asimina obovata', 'Balduina angustifolia', 'Bejaria racemosa', 'Cartrema floridana', 'Carya floridana', 'Ceratiola ericoides', 'Chrysopsis floridana', 'Commelina erecta', 'Conradina grandiflora', 'Dalea feayi', 'Hypericum tenuifolium', 'Ilex opaca', 'Licania michauxii', 'Lyonia ferruginea', 'Lyonia fruticosa', 'Opuntia humifusa', 'Palafoxia feayi', 'Persea humilis', 'Piloblephis rigida', 'Pinus clausa', 'Pityopsis graminifolia', 'Polygonella robusta', 'Quercus chapmanii', 'Quercus geminata', 'Quercus inopina', 'Quercus myrtifolia', 'Sabal etonia', 'Serenoa repens', 'Trichostema dichotomum', 'Vaccinium darrowii', 'Vaccinium myrsinites', 'Ximenia americana', 'Yucca filamentosa', 'Zamia integrifolia']

In [247]:
knownScrubSpeciesObsSub=np.random.choice(knownScrubSpeciesObs, int(len(knownScrubSpeciesObs)*.3))

In [248]:
knownScrubSpeciesObsSub

array(['Polygonella robusta', 'Bejaria racemosa', 'Palafoxia feayi',
       'Balduina angustifolia', 'Vaccinium myrsinites',
       'Lyonia ferruginea', 'Quercus geminata', 'Pinus clausa',
       'Vaccinium darrowii', 'Palafoxia feayi', 'Pinus clausa',
       'Lyonia fruticosa', 'Ceratiola ericoides', 'Ilex opaca',
       'Dalea feayi', 'Ilex opaca', 'Yucca filamentosa',
       'Ceratiola ericoides', 'Serenoa repens', 'Bejaria racemosa',
       'Ximenia americana', 'Opuntia humifusa', 'Quercus chapmanii',
       'Opuntia humifusa', 'Serenoa repens', 'Ceratiola ericoides',
       'Bejaria racemosa', 'Polygonella robusta', 'Bejaria racemosa',
       'Quercus geminata', 'Vaccinium myrsinites',
       'Balduina angustifolia', 'Commelina erecta', 'Ximenia americana',
       'Balduina angustifolia', 'Conradina grandiflora',
       'Quercus chapmanii', 'Bejaria racemosa', 'Carya floridana',
       'Commelina erecta', 'Quercus inopina', 'Bejaria racemosa',
       'Piloblephis rigida', 'Polygon

In [249]:
knownScrubSpeciesObsHist = numpy.histogram(knownScrubSpeciesObsSub, bins=plants)

In [251]:
plantCommunitiesHist = {}
for cluster_id in clusterIds:
    plantCommunitiesHist[cluster_id] = numpy.histogram(plantCommunities_df.loc[plantCommunities_df['CLUSTER_ID']==cluster_id]['species'], 
                        bins=plants)
   
    dof = len(knownScrubSpeciesObsHist) - 1 
    stat, p = scipy.stats.chisquare(plantCommunitiesHist[cluster_id][0], knownScrubSpeciesObsHist[0])
    

    critical  = scipy.stats.chi2.ppf(.80, dof)
    print(critical)


    if abs(stat) >= critical:
        result = 'reject H0'
    else:
        result = 'fail to reject H0'

    print("%s, %s, %s, %s, %s" stat, p, dof, critical, result)


326.12493846023256 6.342536689526783e-50 1
1.642374415149818
Not a match (reject H0)
337.4459568050815 3.733727550740977e-52 1
1.642374415149818
Not a match (reject H0)
250.9085672002501 2.4209338259141807e-35 1
1.642374415149818
Not a match (reject H0)
2192.048142414861 0.0 1
1.642374415149818
Not a match (reject H0)
342.7350562234463 3.3701784731895105e-53 1
1.642374415149818
Not a match (reject H0)
245.37891419072096 2.729434179731585e-34 1
1.642374415149818
Not a match (reject H0)
277.43334129638475 1.972269401595248e-40 1
1.642374415149818
Not a match (reject H0)
312.57857211158296 2.885269048609857e-47 1
1.642374415149818
Not a match (reject H0)
338.88483954985503 1.941565088746408e-52 1
1.642374415149818
Not a match (reject H0)
349.61938680084967 1.464787736778814e-54 1
1.642374415149818
Not a match (reject H0)
348.3105155177826 2.660117854439233e-54 1
1.642374415149818
Not a match (reject H0)
347.1217789632483 4.5725860168605905e-54 1
1.642374415149818
Not a match (reject H0)


In [246]:
for cluster_id in clusterIds:
    print(plantCommunitiesHist[cluster_id])

(array([0, 0, 2, 3, 0, 0, 9, 0, 0, 0, 2, 0, 1, 2, 8, 0, 0, 0, 0, 0, 1, 0,
       0, 2, 4, 0, 4, 1, 3, 0, 0, 3, 0, 0], dtype=int64), array(['Asclepias tuberosa', 'Asimina obovata', 'Balduina angustifolia',
       'Bejaria racemosa', 'Cartrema floridana', 'Carya floridana',
       'Ceratiola ericoides', 'Chrysopsis floridana', 'Commelina erecta',
       'Conradina grandiflora', 'Dalea feayi', 'Hypericum tenuifolium',
       'Ilex opaca', 'Licania michauxii', 'Lyonia ferruginea',
       'Lyonia fruticosa', 'Opuntia humifusa', 'Palafoxia feayi',
       'Persea humilis', 'Piloblephis rigida', 'Pinus clausa',
       'Pityopsis graminifolia', 'Polygonella robusta',
       'Quercus chapmanii', 'Quercus geminata', 'Quercus inopina',
       'Quercus myrtifolia', 'Sabal etonia', 'Serenoa repens',
       'Trichostema dichotomum', 'Vaccinium darrowii',
       'Vaccinium myrsinites', 'Ximenia americana', 'Yucca filamentosa',
       'Zamia integrifolia'], dtype='<U22'))
(array([1, 2, 1, 0, 2, 2, 1, 0

       'Zamia integrifolia'], dtype='<U22'))
(array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 3, 2, 0, 0, 0, 3, 0,
       0, 1, 3, 0, 1, 0, 9, 0, 0, 3, 0, 1], dtype=int64), array(['Asclepias tuberosa', 'Asimina obovata', 'Balduina angustifolia',
       'Bejaria racemosa', 'Cartrema floridana', 'Carya floridana',
       'Ceratiola ericoides', 'Chrysopsis floridana', 'Commelina erecta',
       'Conradina grandiflora', 'Dalea feayi', 'Hypericum tenuifolium',
       'Ilex opaca', 'Licania michauxii', 'Lyonia ferruginea',
       'Lyonia fruticosa', 'Opuntia humifusa', 'Palafoxia feayi',
       'Persea humilis', 'Piloblephis rigida', 'Pinus clausa',
       'Pityopsis graminifolia', 'Polygonella robusta',
       'Quercus chapmanii', 'Quercus geminata', 'Quercus inopina',
       'Quercus myrtifolia', 'Sabal etonia', 'Serenoa repens',
       'Trichostema dichotomum', 'Vaccinium darrowii',
       'Vaccinium myrsinites', 'Ximenia americana', 'Yucca filamentosa',
       'Zamia integrifolia'], 